language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

before_script:
  - |
      cargo install --git https://github.com/semantic-rs/semantic-rs --debug --force

cache: cargo

after_success:
  - cargo doc --no-deps

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GH_TOKEN # Set in travis-ci.org dashboard
    on:
      branch: master
    local_dir: ./target/doc

  - provider: script
    script:
      - semantic-rs
    on:
      branch: master
