language: rust

rust:
  - stable
  - beta
  - nightly

# only trigger a build on the master branch
branches:
  only:
    - master

before_script:
  - |
      cargo install --git https://github.com/semantic-rs/semantic-rs --debug &&
      export PATH=$HOME/.cargo/bin:$PATH &&

matrix:
  allow_failures:
    - rust: nightly

cache: cargo

before_deploy:
  - cargo doc --no-deps

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
    on:
      branch: master
    local_dir: ./target/doc

  - provider: script
    script:
      - export GH_TOKEN=$GITHUB_TOKEN
      - semantic-rs
    on:
      branch: master
