language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

cache: cargo

after_success:
  - cargo doc --no-deps

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
    on:
      branch: master
    local_dir: ./target/doc

  - provider: script
    script:
      - |
        cargo install --git https://github.com/semantic-rs/semantic-rs --debug &&
        PATH=$HOME/.cargo/bin:$PATH:GH_TOKEN=$GITHUB_TOKEN semantic-rs
    on:
      branch: master
