language: rust
rust: nightly
cache: cargo

branches:
  # don't re-run builds after semver tagging
  except:
    - /^v[0-9]+\.[0-9]+\.[0-9]+/



stages:
  - name: build
    script:
      - |
          cargo build &&
          cargo test &&
          cargo bench

  # deploy to crates
  - name: deploy
    if: branch = master AND type = push
    script: scripts/deploy.sh
