language: rust
rust: nightly
cache: cargo

branches:
  # don't re-run builds after semver tagging
  except:
    - /^v[0-9]+\.[0-9]+\.[0-9]+/

script:
  - |
      cargo build &&
      cargo test &&
      cargo bench &&
      cargo doc --no-deps

deploy:
  # deploy to crates
  - provider: script
    skip_cleanup: true
    on:
      branch: master
      condition: $TRAVIS_PULL_REQUEST = "false"
    script: scripts/deploy.sh

  # deploy to github pages
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
    on:
      branch: master
    local_dir: ./target/doc
