[package]
name = "organelle"
version = "0.1.0"
authors = ["Andrew J Westlake <kelixes@gmail.com>"]

[dependencies]
error-chain = "*"
futures = "*"
tokio = "*"
tokio-core = "*"
uuid = { version = "*", features = ["serde", "v4"] }
